# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    #http_method_override: true

    session:
        # handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true

    mailer:
        envelope:
            sender: website@example.com
        headers:
            from: no-reply@example.com
            X-Auto-Response-Suppress: "OOF, DR, RN, NRN, AutoReply"

    form:
        legacy_error_messages: false
