security:
    enable_authenticator_manager: true

    encoders:
        App\Entity\User: bcrypt

    providers:
        users_in_memory: { memory: null }

        local:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|build|bundles|css|images|js|translations)/
            security: false

        main:
            lazy: true
            provider: local

            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator

            logout:
                path: user_logout
                target: home_index

            login_throttling:
                max_attempts: 300

            switch_user: true

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        - { path: "^/([a-z]{2}\/)?admin",                   requires_channel: https,    roles: [IS_AUTHENTICATED_FULLY,         ROLE_ADMIN  ] }
        - { path: "^/([a-z]{2}\/)?account/login",           requires_channel: https,    roles: [IS_AUTHENTICATED_ANONYMOUSLY                ] }
        - { path: "^/([a-z]{2}\/)?account/register",        requires_channel: https,    roles: [IS_AUTHENTICATED_ANONYMOUSLY                ] }
        - { path: "^/([a-z]{2}\/)?account",                 requires_channel: https,    roles: [IS_AUTHENTICATED_FULLY                      ] }
        - { path: "^/([a-z]{2}\/)?",                        requires_channel: https,    roles: [                                            ] }
